version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD:-}"
    command: >
      redis-server 
      --save "20 1" 
      --loglevel "warning" 
      --requirepass "${REDIS_PASSWORD}"
    volumes:
      - "./redis:/data"
    networks:
      - my_network

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-mydatabase}"
      POSTGRES_USER: "${POSTGRES_USER:-user}"  
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
    volumes:
      - "./postgres:/var/lib/postgresql/data"
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_EMAIL:-admin@admin.com}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_PASSWORD:-admin}"
    networks:
      - my_network
    depends_on:
      - postgres

  dashboard-service:
    image: advitama/ruker-dashboard-service:${DASHBOARD_VERSION}
    restart: unless-stopped
    ports:
      - "${DASHBOARD_PORT}:8080"
    environment:
      - APP_NAME=Dashboard Service
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DASHBOARD_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - AUTH_API_URL=http://host.docker.internal:${AUTH_PORT}
      - ALLOWED_ORIGINS=http://localhost:3000
    networks:
      - my_network

  auth-service:
    image: advitama/ruker-auth-service:${AUTH_VERSION}
    restart: unless-stopped
    ports:
      - "${AUTH_PORT}:8080"
    environment:
      - APP_NAME=Auth Service
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${AUTH_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - AUTH_APP_URL=http://localhost:3001
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001,https://localhost:${DASHBOARD_PORT}
    networks:
      - my_network

networks:
  my_network: